# Generated by Django 5.0.1 on 2024-02-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_bookcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='bookstore.bookcategory'),
        ),
    ]
