# Generated by Django 5.0.1 on 2024-02-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('coupon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('book', models.ManyToManyField(to='bookstore.book')),
            ],
        ),
    ]
